"use strict";
exports.__esModule = true;
exports.useChatbot = exports.createCustomMessage = exports.createClientMessage = exports.createChatBotMessage = exports.Chatbot = void 0;
var Chatbot_1 = require("./components/Chatbot/Chatbot");
exports.Chatbot = Chatbot_1["default"];
var chatUtils_1 = require("./components/Chat/chatUtils");
exports.createChatBotMessage = chatUtils_1.createChatBotMessage;
exports.createClientMessage = chatUtils_1.createClientMessage;
exports.createCustomMessage = chatUtils_1.createCustomMessage;
var useChatbot_1 = require("./hooks/useChatbot");
exports.useChatbot = useChatbot_1["default"];
exports["default"] = Chatbot_1["default"];
